## Implimentation of Perceptron


In [21]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import joblib # FOR SAVING MY MODEL AS A BINARY FILE
from matplotlib.colors import ListedColormap

plt.style.use("fivethirtyeight") # THIS IS STYLE OF GRAPHS

In [22]:
np.random.randn(3) * 1e-4

array([-5.31594951e-05,  6.19463812e-05,  1.56079853e-04])

In [23]:
-np.ones((4, 1))

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [24]:
1e-4

0.0001

In [46]:
class Perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.randn(3) * 1e-4 # SMALL WEIGHT INIT
        print(f"initial weights before training: \n{self.weights}")
        self.eta = eta # LEARNING RATE
        self.epochs = epochs 


    def activationFunction(self, inputs, weights):
        z = np.dot(inputs, weights) # z = W * X
        print("inputs : ",inputs)
        print("weights : ",weights)
        print("z : ",z)
        return np.where(z > 0, 1, 0) # CONDITION, IF TRUE, ELSE

    def fit(self, X, y):
        self.X = X
        self.y = y

        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # CONCATINATION
        print(f"X with bias: \n{X_with_bias}")

        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch: {epoch}")
            print("--"*10)

            y_hat = self.activationFunction(X_with_bias, self.weights) # foward propagation
            print(f"predicted value after forward pass: \n{y_hat}")
            print("self.y : ",self.y)
            print("y_hat : ",y_hat)
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            print("X_with_bias.T : ",X_with_bias.T)
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error) # backward propagation
            print(f"updated weights after epoch:\n{epoch}/{self.epochs} : \n{self.weights}")
            print("#####"*10)


    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        print("X : ",X)
        print("X_with_bias : ",X_with_bias)
        return self.activationFunction(X_with_bias, self.weights)

    def total_loss(self):
        total_loss = np.sum(self.error)
        print(f"total loss: {total_loss}")
        return total_loss


In [47]:
def prepare_data(df):
    X = df.drop("y", axis=1)

    y = df["y"]

    return X, y

In [48]:
AND = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y": [0,0,0,1],
}

df = pd.DataFrame(AND)

df

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [49]:
#### Delete below

In [50]:
X,y = prepare_data(df)

In [51]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [52]:
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [53]:
ETA = 0.3 # 0 and 1
EPOCHS = 10

In [54]:
model = Perceptron(eta=ETA, epochs=EPOCHS)

initial weights before training: 
[-1.28207981e-04  4.77045550e-05 -3.51547268e-05]


In [55]:
model.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch: 0
--------------------
inputs :  [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
weights :  [-1.28207981e-04  4.77045550e-05 -3.51547268e-05]
z :  [ 3.51547268e-05  8.28592818e-05 -9.30532542e-05 -4.53486992e-05]
predicted value after forward pass: 
[1 1 0 0]
self.y :  0    0
1    0
2    0
3    1
Name: y, dtype: int64
y_hat :  [1 1 0 0]
error: 
0   -1
1   -1
2    0
3    1
Name: y, dtype: int64
X_with_bias.T :  [[ 0.  0.  1.  1.]
 [ 0.  1.  0.  1.]
 [-1. -1. -1. -1.]]
updated weights after epoch:
0/10 : 
[2.99871792e-01 4.77045550e-05 2.99964845e-01]
##################################################
--------------------
for epoch: 1
--------------------
inputs :  [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
weights :  [2.99871792e-01 4.77045550e-05 2.99964845e-01]
z :  [-2.99964845e-01 -2.99917141e-01 -9.30532542e-05 -4.53486992e-05]
predicted value af

In [56]:
_ = model.total_loss()

total loss: 0


In [57]:
inputs = np.array([[1,1]])
model.predict(inputs)

X :  [[1 1]]
X_with_bias :  [[ 1.  1. -1.]]
inputs :  [[ 1.  1. -1.]]
weights :  [0.59987179 0.3000477  0.59996485]
z :  [0.29995465]


array([1])

In [ ]:
##### Delete above

In [23]:
X,y = prepare_data(df)

ETA = 0.3 # 0 and 1
EPOCHS = 10

model = Perceptron(eta=ETA, epochs=EPOCHS)
model.fit(X, y)

_ = model.total_loss()


initial weights before training: 
[-7.68837545e-05 -1.75020657e-05 -8.06340726e-05]
X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch: 0
--------------------
predicted value after forward pass: 
[1 1 1 0]
error: 
0   -1
1   -1
2   -1
3    1
Name: y, dtype: int64
updated weights after epoch:
0/10 : 
[-7.68837545e-05 -1.75020657e-05  5.99919366e-01]
##################################################
--------------------
for epoch: 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:
1/10 : 
[0.29992312 0.2999825  0.29991937]
##################################################
--------------------
for epoch: 2
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch:
2/10 : 
[-7.68837545e-05 -1.75020657e-05  8.99919366e-01]
#############

In [24]:
model.predict(X)

array([0, 0, 0, 1])

In [25]:
X.values

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [26]:
inputs = np.array([[1,1], [0,1]])
model.predict(inputs)

array([1, 0])

In [27]:
def save_model(model, filename):
    
    model_dir = "models"
    os.makedirs(model_dir, exist_ok=True) # ONLY CREATE IF MODEL_DIR DOESN"T EXISTS
    filePath = os.path.join(model_dir, filename) # model/filename
    joblib.dump(model, filePath)

In [28]:
save_model(model, "and.model")

In [29]:
loaded_model = joblib.load("models/and.model")
loaded_model.predict(inputs)

array([1, 0])